#!/usr/bin/env python3
"""Generate include/jieba_separator_bitmap.h from Unicode character data.

All BMP codepoints with General Category P (punctuation) or Z (separator/space),
plus ASCII control characters (0x00-0x1F), are marked as separators.
"""
import unicodedata

bitmap = [0] * 1024  # 1024 * 64 bits = 65536 bits (full BMP)

for cp in range(0x10000):
    cat = unicodedata.category(chr(cp))
    is_sep = cat[0] in ('P', 'Z') or cp <= 0x1F
    if is_sep:
        bitmap[cp >> 6] |= (1 << (cp & 63))

total = sum(bin(x).count('1') for x in bitmap)

with open("include/jieba_separator_bitmap.h", "w") as f:
    f.write("#pragma once\n\n")
    f.write("#include <cstdint>\n\n")
    f.write("namespace jieba_separator {\n\n")
    f.write("/// Unicode separator bitmap: marks all BMP codepoints with General Category\n")
    f.write("/// P (punctuation) or Z (separator/space), plus ASCII control chars (0x00-0x1F).\n")
    f.write(f"/// Generated by tools/generate_separator_bitmap.py — {total} codepoints marked.\n")
    f.write("// clang-format off\n")
    f.write("static constexpr uint64_t separator_bitmap[1024] = {\n")
    for i in range(0, 1024, 8):
        chunk = bitmap[i:i+8]
        hex_vals = ", ".join(f"0x{v:016X}" for v in chunk)
        f.write(f"    {hex_vals},\n")
    f.write("};\n")
    f.write("// clang-format on\n\n")
    f.write("inline bool isSeparator(uint16_t r)\n")
    f.write("{\n")
    f.write("    return (separator_bitmap[r >> 6] >> (r & 63)) & 1;\n")
    f.write("}\n\n")
    f.write("} // namespace jieba_separator\n")

print(f"Generated include/jieba_separator_bitmap.h ({total} separator codepoints)")
